### ISSUE TITLE
8.1 Compatibility?

### ISSUE THREAD

**Issue by peterpociask** [zigor/morph#1]
Is there an 8.1 compatible branch for this library?

**Comment by zigor** [comment]
Use [the same version](https://github.com/zigor/morph/releases/tag/v1.1) that was build for Sitecore 8.2.

**Comment by peterpociask** [comment]
Thanks.  I am getting a compilation error:

'Constants' does not contain a definition for 'Routes'  
RegisterFormRouteReplacement.cs 29

Is it possible routes was added in the 8.2 release?

**Comment by zigor** [comment]
I removed that file, it is not required

**Comment by zigor** [comment]
managed to run the [package](https://github.com/zigor/morph/releases/latest) on Sitecore 8.1
